### ISSUE TITLE
axios

### ISSUE THREAD

**Issue by hoseinmirian** [JanssenBrm/api-gateway#2]
Dear @JanssenBrm ,

when we use http proxy we are needless of using axios right?

**Comment by JanssenBrm** [comment]
Dear @hoseinmirian,

That is correct, the module `http-proxy-middleware` will be responsible to redirect the incoming requests to specified endpoints. However, if you would require some more advanced features when proxying requests, you could use other libraries as `axios` as well.

Hopefully, this answers your question!

Cheers!
